### ISSUE TITLE
Install error: ’multicast’ does not appear to be an IPv4 or IPv6 network

### ISSUE THREAD

**Issue by BeyondB13** [openmediavault/openmediavault-docs#93]
Greetings everyone,
I was trying to install openmediavault, while running in the error above.
This is the first time for me to submit an issue, so if I am not doing it well enough I am very open for criticism.

First let me round up my setup and the i[nstallation instructions](https://openmediavault.readthedocs.io/en/latest/installation/on_debian.html) I used.
I have an homeserver which runs Proxmox, with an Debian 10 container (lxc) and after executing the the last step (omv-confdbadm populate) in mentioned instruction I ran in following error code:
’multicast’ does not appear to be an IPv4 or IPv6 network

Here is my the complete output of my error message:
```
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
ValueError: 'multicast' does not appear to be an IPv4 or IPv6 network
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 112, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 220, in call
    self.opts, data, func, args, kwargs
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1764, in routes
    routes_ = _ip_route_linux()
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 609, in _ip_route_linux
    address_mask = convert_cidr(comps[0])
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1232, in convert_cidr
    cidr = calc_net(cidr)
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1255, in calc_net
    return __utils__["network.calc_net"](ip_addr, netmask)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/network.py", line 1185, in calc_net
    return str(ipaddress.ip_network(ipaddr, strict=False))
  File "/usr/lib/python3/dist-packages/salt/ext/ipaddress.py", line 108, in ip_network
    address)
ValueError: 'multicast' does not appear to be an IPv4 or IPv6 network
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3003', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 449, in salt_call
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 112, in run
    ret = self.call()
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 220, in call
    self.opts, data, func, args, kwargs
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1764, in routes
    routes_ = _ip_route_linux()
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 609, in _ip_route_linux
    address_mask = convert_cidr(comps[0])
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1232, in convert_cidr
    cidr = calc_net(cidr)
  File "/usr/lib/python3/dist-packages/salt/modules/network.py", line 1255, in calc_net
    return __utils__["network.calc_net"](ip_addr, netmask)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/utils/network.py", line 1185, in calc_net
    return str(ipaddress.ip_network(ipaddr, strict=False))
  File "/usr/lib/python3/dist-packages/salt/ext/ipaddress.py", line 108, in ip_network
    address)
ValueError: 'multicast' does not appear to be an IPv4 or IPv6 network
```

Due the nature of being network related here my network configuration. The IPv6 address has been altered due to safety reasons:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if22: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 76:47:e0:5e:02:ce brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.30.1.47/24 brd 10.30.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a02:2363:262:f504:7489:e0ff:fe5e:2ce/64 scope global dynamic mngtmpaddr 
       valid_lft 7105sec preferred_lft 3505sec
    inet6 fe80::7489:e0ff:fe5e:2ce/64 scope link 
       valid_lft forever preferred_lft forever
default via 10.30.1.1 dev eth0 onlink 
10.30.1.0/24 dev eth0 proto kernel scope link src 10.30.1.47 
::1 dev lo proto kernel metric 256 pref medium
2a02:2363:262:f504::/64 dev eth0 proto kernel metric 256 expires 7104sec pref medium
fe80::/64 dev eth0 proto kernel metric 256 pref medium
default via fe80::2e91:abff:fe91:87d9 dev eth0 proto ra metric 1024 expires 1704sec hoplimit 255 pref medium
```

If you need further informations please let me know and thank you for your help.

**Comment by ryecoaaron** [comment]
OMV doesn’t work in containers like lxc or docker.

**Comment by votdev** [comment]
This is a known bug in SaltStack, see https://github.com/saltstack/salt/pull/59829 and https://github.com/saltstack/salt/issues/58377. OMV6 has a patch top workaround this issue (https://github.com/openmediavault/openmediavault/pull/1062).

You can give it a try with OMV6 (Debian 11), but as @ryecoaaron mentioned, OMV is not designed to run in containers. If it works, then fine, but this is not supported officially.
